class UserNotFoundError(Exception):
    pass


class TaskNotFoundError(Exception):
    pass
